services:
  section_field.generator.doctrine_config_generator:
    class: Tardigrades\SectionField\Generator\DoctrineConfigGenerator
    arguments:
      - '@section_field.manager.doctrine.field_manager'
      - '@section_field.manager.doctrine.field_type_manager'
      - '@section_field.manager.doctrine.section_manager'

  section_field.doctrine.create.section:
    class: Tardigrades\SectionField\Service\DoctrineSectionCreator
    arguments:
      - '@doctrine.orm.entity_manager'

  section_field.doctrine.read.section:
    class: Tardigrades\SectionField\Service\DoctrineSectionReader
    arguments:
      - '@doctrine.orm.entity_manager'

  section_field.doctrine.delete.section:
    class: Tardigrades\SectionField\Service\DoctrineSectionDeleter
    arguments:
      - '@doctrine.orm.entity_manager'

# This is the configuration that assumes you use the sexy-field-doctrine package
# If you have more generators, or more readers and writers, override this configuration
# in your own application services configuration.
  section_field.generator:
    class: Tardigrades\SectionField\Generator\Generators
    arguments:
      -
        - '@section_field.generator.entity_generator'
        - '@section_field.generator.doctrine_config_generator'

  section_field.create.section:
    class: Tardigrades\SectionField\Service\CreateSection
    arguments:
      -
        - '@section_field.doctrine.create.section'

  section_field.read.section:
    class: Tardigrades\SectionField\Service\ReadSection
    arguments:
      -
        - '@section_field.doctrine.read.section'
      - '@section_field.manager.doctrine.section_manager'

  section_field.delete.section:
    class: Tardigrades\SectionField\Service\DeleteSection
    arguments:
      -
        - '@section_field.doctrine.delete.section'
